#!/bin/sh
### BEGIN INIT INFO
# Provides:          oh-dbus-daemon
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Openheating DBus Daemon
# Description:       blah
### END INIT INFO

set -e

OH_SERVICENAME=oh-dbus-daemon
OH_DESC="Openheating DBus Daemon"
OH_PROGRAM=/usr/bin/dbus-daemon
OH_PROGRAM_ARGS="--config-file=/home/jfasch/oh-dbus.conf"
    
. ./oh-service
