#!/usr/bin/python3

import openheating.dbus.dbus_names as dbus_names
from openheating.core.thermometer import Thermometer
from openheating.dbus.dbus_thermometer_object import DBusThermometerObject

from pydbus import SessionBus
from gi.repository import GLib
import time


class MyThermometer(Thermometer):
    def get_temperature(self):
        return 21.0

loop = GLib.MainLoop()    
bus = SessionBus()
bus.publish(dbus_names.THERMOMETER_IFACE, ('/a/b', DBusThermometerObject(MyThermometer())))

loop.run()
